require_relative 'config/application'
require 'rom-sql'
require 'rom/sql/rake_task'

namespace :db do
  task :setup do
    Projects::Application.start(:db)
    config = Projects::Application['db.config']
    config.gateways[:default].use_logger(Logger.new($stdout))
  end
end
