require 'rom/sql/rake_task'

require_relative 'lib/projects'

namespace :db do
  task :setup do
    Projects::Application.start(:persistence)
    ROM::SQL::RakeSupport.env = ROM.container(:sql,Projects::Application["db.connection"])
  end
end
